### PR TITLE
Use the proper cast for lsxpack header platform independent

### LINKED ISSUE #5: Doesn't build on arm64 linux
Linux debian-4gb-fsn1-1 6.1.0-11-arm64 #1 SMP Debian 6.1.38-4 (2023-08-08) aarch64 GNU/Linux

```
error[E0308]: mismatched types
   --> /home/mozgiii/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ls-qpack-0.1.2/src/decoder.rs:374:31
    |
374 |             this.header.buf = this.decoding_buffer.as_mut_ptr() as *mut i8;
    |             ---------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*mut u8`, found `*mut i8`
    |             |
    |             expected due to the type of this binding
    |
    = note: expected raw pointer `*mut u8`
               found raw pointer `*mut i8`

error[E0308]: mismatched types
   --> /home/mozgiii/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ls-qpack-0.1.2/src/header.rs:199:18
    |
199 |             buf: header.buffer.as_mut_ptr() as *mut i8,
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*mut u8`, found `*mut i8`
    |
    = note: expected raw pointer `*mut u8`
               found raw pointer `*mut i8`
```

I'm not sure why is this.

### PR DESCRIPTION
**Pull request by BiagioFesta**
Fixes: https://github.com/BiagioFesta/ls-qpack-rs/issues/5

### CODE REVIEW

**Comment by MOZGIII** [comment]
```
 Compiling ls-qpack v0.1.2 (https://github.com/BiagioFesta/ls-qpack-rs.git?branch=fix-cast#72e9410b)
error[E0412]: cannot find type `c_char` in this scope
   --> /home/mozgiii/.cargo/git/checkouts/ls-qpack-rs-8c1ccf7403e7ee19/72e9410/ls-qpack/src/decoder.rs:375:73
    |
375 |             this.header.buf = this.decoding_buffer.as_mut_ptr() as *mut c_char;
    |                                                                         ^^^^^^
    |
help: a builtin type with a similar name exists
    |
375 |             this.header.buf = this.decoding_buffer.as_mut_ptr() as *mut char;
    |                                                                         ~~~~
help: consider importing one of these items
    |
277 +     use core::ffi::c_char;
    |
277 +     use crate::decoder::c_char;
    |
277 +     use libc::c_char;
    |
277 +     use std::ffi::c_char;
    |
      and 1 other candidate

For more information about this error, try `rustc --explain E0412`.
error: could not compile `ls-qpack` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

Consider adding Github Actions for CI at the very least they'll show when the code doesn't compile.

**Comment by BiagioFesta** [comment]
> Consider adding Github Actions for CI at the very least they'll show when the code doesn't compile.

Yeah, it's in the TODO: https://github.com/BiagioFesta/ls-qpack-rs/issues/7

**Comment by MOZGIII** [comment]
The code compiles now; need to test the actual runtime though, stay tuned.

**Comment by hironichu** [comment]
I've been able to try this patch with wtransport on multiple arm machines (Raspberry and Ampere servers on Oracle cloud) and this seems to be working super well !

**Comment by BiagioFesta** [comment]
Perfect thanks!

**Pull request merged**
